apiVersion: config.kio.kasten.io/v1alpha1
kind: BlueprintBinding
metadata:
  name: mongo-binding-vm
  namespace: kasten-io
spec:
  blueprintRef:
    name: mongo-hooks-vm
    namespace: kasten-io
  resources:
    matchAll:
    - type:
        operator: In
        values:
        - group: kubevirt.io
          resource: virtualmachines
    - annotations:
        key: kanister.kasten.io/blueprint
        operator: DoesNotExist    
    - labels:
        key: usage
        operator: In
        values:
        - mongodb
